# Generated by Django 5.2.6 on 2025-09-18 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
