# Generated by Django 5.2.6 on 2025-09-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_instructor_alter_enrollment_course_and_more'),
        ('courses', '0003_course_students_alter_course_instructor'),
    ]

    operations = [
    ]
